language: python
python:
  - 2.7
services:
  - postgresql
install:
  - sudo apt-get install libffi libffi-dev
  - sudo apt-get install libgit2 libgit2-dev
  - pip install -r requirements.txt
script:
  - python manage.py test
