language: python
python:
  - 2.7
services:
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
notifications:
  email:
    recipients:
      - gitterdone@wpi.edu
  irc: "anika.crepinc.com#gitterdone"
